version: "3.6"
services:
  database:
    image: mysql:8
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    networks:
      - test-task-network
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: requestdb
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    volumes:
      - ./init:/docker-entrypoint-initdb.d

  app:
    build:
      context: .
      args:
        JAR_FILE: target/multy_thread_counter-1.0-SNAPSHOT-exec.jar
    ports:
      - "8001:8001"
    depends_on:
      - database
    restart: always
    networks:
      - test-task-network

networks:
  test-task-network:
    driver: bridge
